- hosts: front
  gather_facts: true
  become:
    true
  become_method:
    sudo
  become_user:
    root
  remote_user:
    anclave-777
  roles:
   - Install_Nginx_LetsEncrypt
   - Install_Proxy
   - Node_exp
